CREATE TABLE shopping (
  ID SERIAL PRIMARY KEY,
  item VARCHAR (255) NOT NULL,
  done BOOLEAN DEFAULT FALSE,
  uid VARCHAR (255) NOT NULL
);

CREATE TABLE postit (
  ID SERIAL PRIMARY KEY,
  content VARCHAR (255) NOT NULL,
  uid VARCHAR (255) NOT NULL
);

CREATE TABLE photos (
  ID SERIAL PRIMARY KEY,
  url VARCHAR (255) NOT NULL,
  title VARCHAR (255) NOT NULL,
  public_id VARCHAR (255) NOT NULL,
  uid VARCHAR (255) NOT NULL
);
